# Part of components_collector project
# See LICENSE and README for more info on usage



$(info components_collector makefile started)

$(info COMPONENTS_COLLECTOR_PATH = ${COMPONENTS_COLLECTOR_PATH})
$(info COMPONENTS_DIR = ${COMPONENTS_DIR})
$(info BUILD_DIR = ${BUILD_DIR})
$(info COMPONENTS_CODE_PATH = ${COMPONENTS_CODE_PATH})

COMPONENTS_COLLECTOR_PATH ?= ./collect_components.py
COMPONENTS_CODE_PATH ?= ${BUILD_DIR}/components_collector.c
COMPONENTS_INCLUDE_PATH ?= ${BUILD_DIR}/components.h
COMPONENTS_OBJ_PATH ?= $(patsubst %.c,%.o,$(COMPONENTS_CODE_PATH))

OBJS += ${COMPONENTS_OBJ_PATH}

# Uses typical compile implementation
{COMPONENTS_OBJ_PATH}: ${COMPONENTS_CODE_PATH} ${COMPONENTS_INCLUDE_PATH}

PATH_TO_COMPONENTS_CODE = $(shell dirname $(COMPONENTS_CODE_PATH))
$(info PATH_TO_COMPONENTS_CODE = ${PATH_TO_COMPONENTS_CODE})

# ${COMPONENTS_CODE_PATH}: | ${COMPONENTS_CODE_PATH}

${COMPONENTS_CODE_PATH} ${COMPONENTS_INCLUDE_PATH}: ${COMPONENTS_DIR} ${COMPONENTS_COLLECTOR_PATH}
	$(COMPONENTS_COLLECTOR_PATH) \
		${COMPONENTS_CODE_PATH} \
		$(COMPONENTS_INCLUDE_PATH) \
		${COMPONENTS_DIR}


